#!/bin/bash
set -e

function gather_tags {
  npm view '@redocly/cli' versions --json | jq '.[]' --raw-output
}

function delete_ignored_tags {
  for tag in $( gather_tags | grep -f .tagignore ); do
    if git show-ref --tags | grep "tags/v${tag}$"
    then
      echo "Delete Tag ${tag}"
      git tag -d v${tag} && git push origin :refs/tags/v${tag}
    fi
  done
}

function build_missing_tags {
  commit=$(git rev-parse HEAD)
  for tag in $( gather_tags | grep -v -f .tagignore ); do
    echo -n "Tag: v${tag} ... "
    if git show-ref --tags | grep "tags/v${tag}$" &> /dev/null
    then
      echo 'is existing'
    else
      echo 'needs building'
      sed -i "s/REDOC_CLI_VERSION=.*/REDOC_CLI_VERSION=${tag}/" Dockerfile
      git add Dockerfile && git commit -m "using version v${tag}"
      git tag "v${tag}" && git push --tags
      git reset --hard $commit
    fi
  done
}

delete_ignored_tags
build_missing_tags
